### ISSUE TITLE
Track allocations larger than N.

### ISSUE THREAD

**Issue by epasveer** [itaych/MEM_debug#2]
Is it possible to add a feature to track allocations larger than N bytes. N being set by an environment variable.

I'm looking to track very large allocations (> 1gb) and ignore smaller ones. When the malloc() happens, a message is printed (including caller address) and when the matching free() happens, a message is printed. These messages have a timestamp for their occurrence.

Rational.
I have a program that does many of these large allocations and frees during its life (around 8 hours). I want to make sure the deallocations are happening during the the program and not just at the end.

BTW, this tool can be very helpful to some. Thanks for your work.

**Comment by itaych** [comment]
Hi, thanks for your comment. This is the sort of need I run into occasionally myself when debugging, but the thing is that every time the need is for something a little different. Sometimes it's to report allocations beyond a certain size. Sometimes it's to catch cases where the total memory allocation is growing unboundedly. Sometimes it's to check whether a certain thread's allocations pass some threshold. Etc etc.

Since there is no end to these kinds of requests I basically decided not to clutter the code with them, and just hard-code this sort of thing whenever needed.

Your request is also particularly difficult because you want to print a message from within malloc - which can be catastrophic if the print function itself needs to allocate memory. You really don't want to do this with a generic logging function.

Look at function mem_debug_posix_memalign. At line 358 there is a check "if (size > MAX_ALLOC)" which aborts if the allocation is beyond a very large size. (I assume you've already changed MAX_ALLOC to accommodate your huge allocations.) Just before or after that you can add your own check, and print your message. To prevent recursive memory allocations you should only use low level system calls like write(), which is why I wrote some "safe print" functions that I recommend you use, but note that they offer far less formatting functionality than printf. See how I use them for an example.

If you want to add a time stamp, again I warn that calling time stamp related functions (e.g. getting the current time, formatting it to human readable format) from within malloc may or may not work. Reading the N environment variable should probably be done elsewhere, or just use a #define.

Good luck :)
